// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimulatorApp.Infrastructure.Data;

#nullable disable

namespace SimulatorApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218205032_RemoveThresholdFieldForAlerts")]
    partial class RemoveThresholdFieldForAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimulatorApp.Core.Models.AlertLog", b =>
                {
                    b.Property<long>("AlertLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AlertLogId"));

                    b.Property<long>("AlertRuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TriggerValue")
                        .HasColumnType("double precision");

                    b.HasKey("AlertLogId");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("AlertLogs");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.AlertRule", b =>
                {
                    b.Property<long>("AlertRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AlertRuleId"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double?>("RangeMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("RangeMin")
                        .HasColumnType("double precision");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint");

                    b.HasKey("AlertRuleId");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeviceId"));

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.Sensor", b =>
                {
                    b.Property<long>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SensorId"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.HasKey("SensorId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.StateChangeLog", b =>
                {
                    b.Property<long>("StateChangeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StateChangeLogId"));

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StateChangeLogId");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("StateChangeLogs");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.StatusChangeLog", b =>
                {
                    b.Property<long>("StatusChangeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StatusChangeLogId"));

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StatusChangeLogId");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("StatusChangeLogs");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.TelemetryLog", b =>
                {
                    b.Property<long>("TelemetryLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelemetryLogId"));

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.Property<long>("SensorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("TelemetryLogId");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("TelemetryLogs");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.AlertLog", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimulatorApp.Core.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.AlertRule", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.Sensor", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.Device", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.StateChangeLog", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.Sensor", "Sensor")
                        .WithMany("StateChanges")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.StatusChangeLog", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.Sensor", "Sensor")
                        .WithMany("StatusChanges")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.TelemetryLog", b =>
                {
                    b.HasOne("SimulatorApp.Core.Models.Sensor", "Sensor")
                        .WithMany("Telemetries")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.Device", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SimulatorApp.Core.Models.Sensor", b =>
                {
                    b.Navigation("StateChanges");

                    b.Navigation("StatusChanges");

                    b.Navigation("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
